seed: 0

dtype: double

data:
    nbursts: 5 # number of bursts selected randomly from every trajectory
    memory: 0 #nonnegative integer
    multi_steps: 5 # positive integer
    problem_dim: 1
    problem_type: "1d_regular" # "1d_regular", "2d_regular", "1d_irregular", "2d_irregular"

network:
    blocks: 1
    depth: 3 # number of hidden layers
    width: 60 # number of neurons
    activation: "gelu"

training:
    modes: 10
    device: "cpu" #"cpu", "cuda"
    epochs: 500
    batch_size: 10
    optimizer: "adam"
    scheduler: "cosine" # "cosine"， "none"， "cyclic_cosine"
    learning_rate: 0.001
    verbose: 10 # print loss every verbose epochs
    loss: "mse"
    save_path: "./model"
