seed: 0

dtype: double

data:
    problem_type: ode # pde
    nbursts: 5 # number of bursts selected from every trajectory
    memory: 0 #nonnegative integer
    multi_steps: 10 # positive integer
    problem_dim: 3

network:
    depth: 3 # number of hidden layers
    width: 10 # number of neurons
    activation: "gelu"

training:
    device: "cpu" #"cpu", "cuda"
    epochs: 500
    batch_size: 100
    optimizer: "adam"
    scheduler: "cosine" # "cosine"， "none"， "cyclic_cosine"
    learning_rate: 0.001
    verbose: 10 # print loss every verbose epochs
    loss: "mse"
    save_path: "./prior_model"
